// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class Avaliacao
    {
        public int AvaliacaoId { get; set; }
        public int PedidoDetalheId { get; set; }
        public int? PedidoId { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int? QuantidadeEstrela { get; set; }
        public string AvaliacaoUtil { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual PedidoDetalhe PedidoDetalhe { get; set; }
    }
}