// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int ClienteId { get; set; }
        public int? EstadoId { get; set; }
        public int? CidadeId { get; set; }
        public string NomeCliente { get; set; }
        public string Email { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}