// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class Estado
    {
        public Estado()
        {
            Cidade = new HashSet<Cidade>();
        }

        public int EstadoId { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}