// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class Pedido
    {
        public Pedido()
        {
            PedidoDetalhe = new HashSet<PedidoDetalhe>();
        }

        public int PedidoId { get; set; }
        public int ClienteId { get; set; }
        public decimal? ValorTotal { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<PedidoDetalhe> PedidoDetalhe { get; set; }
    }
}