// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class PedidoDetalhe
    {
        public PedidoDetalhe()
        {
            Avaliacao = new HashSet<Avaliacao>();
        }

        public int PedidoDetalheId { get; set; }
        public int ProdutoId { get; set; }
        public int PedidoId { get; set; }
        public int? Quantidade { get; set; }
        public decimal? ValorProduto { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ICollection<Avaliacao> Avaliacao { get; set; }
    }
}