// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevIO.Business.Models
{
    public partial class Produto
    {
        public Produto()
        {
            ImagemProduto = new HashSet<ImagemProduto>();
            PedidoDetalhe = new HashSet<PedidoDetalhe>();
        }

        public int ProdutoId { get; set; }
        public string NomeProduto { get; set; }
        public string DescricaoProduto { get; set; }
        public decimal? ValorProduto { get; set; }
        public string Ativo { get; set; }
        public DateTime? DataFabricacao { get; set; }
        public DateTime? DataValidade { get; set; }
        public string ProdutoPromocao { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? DataAlteracao { get; set; }

        public virtual ICollection<ImagemProduto> ImagemProduto { get; set; }
        public virtual ICollection<PedidoDetalhe> PedidoDetalhe { get; set; }
    }
}